- name: Update all packages
  apt:      
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600
- name: Ensure Apache2 is istalled
  apt:
    name: apache2
    state: latest 
  when: ansible_facts['os_family']|lower == 'debian'
  
- name: Enable mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
    - Restart Apache2

- name: Ensure Apache is running
  service:
    name: apache2
    state: started
